name: CI/CD — evaluation-service-tc3 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  ci:
    uses: Pos-Tech-DevOps-DCLT/infra-tc4/.github/workflows/ci-cd-go-template.yaml@main
    with:
      project: evaluation-service
    secrets: inherit